### ISSUE TITLE
Hardware conditions for x86-64-v2 release?

### ISSUE THREAD

**Issue by rwbc** [analog-hors/tantabus#2]
I am following your Tantabus repo for some months and have compiled it already a few times for myself,
but even the x86-64 v2 binary release version doesn't run here. (old Quadcore core2 = yorkfield type cpu)
Is it compiled with hardware popcnt?

Moreover I want to ask, if you want to remain anonymous? I am asking because I am the maintainer of the XB/UCI chronology
and only add non anonymous programs there. Don't feel obliged though, it's just your decision :)
AFAIK your are from Australia, at least that's mentioned in your youtube channel...

https://rwbc-chess.de/chronology.htm

Guenther

**Comment by analog-hors** [comment]
Yeah, v2 requires `popcnt` ([and a few other features](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels)). I updated the release with a baseline release. I didn't do it initially because I wasn't expecting anyone to actually need one.

As for the anonymity thing, yeah, I do wish to remain anonymous (or pseudonymous, as some would say). I'm generally not a fan of tying my real life identity to this, and it's information most don't need anyway. IMO such policies don't achieve much while being overly exclusive.

**Comment by analog-hors** [comment]
The baseline releases should resolve this, so I'm closing this issue. Let me know if they somehow do not run.
