### ISSUE TITLE
"could not checkmate in simple endgames" : aware KkNN is draw ?

### ISSUE THREAD

**Issue by tissatussa** [analog-hors/tantabus#3]
When publishing v1.0.2 you mention : _"A quick fix to a serious bug where Tantabus could not checkmate in simple endgames"_ .. i did not compile this newest version (and i had no problems with v1.0.1) and i don't know which kind of positions this concerns, but it makes me think about some common "simple endgame blindness" of many engines i tested : KkNN is a draw !

Even very strong engines tend to evaluate KkNN as a clear win, not realising at least one pawn is needed for that. Furthermore, here also an exclusion exists : when the opponent has one pawn left on a certain line, the 2 kNights can win because of tempo. Often this also means the opponent can sacrifice a (last) piece for your last pawn to make a draw. There's a nice Wikipedia article about these basic kNight endgames.

Is Tantabus aware of this endgame concept ?

**Comment by analog-hors** [comment]
To avoid such misevaluations, Tantabus has a simple "oracle" that returns results for simple endgames:
https://github.com/analog-hors/tantabus/blob/4148fd3adeee24aaba3aec86cfe8162c7d5d535d/engine/src/search/oracle.rs#L45-L50
The quick fix was for a more serious bug where certain cases of simple endgames like KQK could not be won due to odd interactions with the time manager, search, and TT.
